//go:build ignore

// Copyright (c) 2026 ramsesyok
// SPDX-License-Identifier: MIT

// Run from the repository root: go run scripts/licenses.go [-check].
// This collects notices; it does not determine license compatibility or provenance.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type module struct {
	Path, Version, Dir string
	Main               bool
	Replace            *module
}

type pkg struct {
	Dir      string
	Standard bool
	Module   *module
}

type dependency struct {
	Module module
	Files  map[string]string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	check := flag.Bool("check", false, "fail if the committed notices need regeneration")
	moduleDir := flag.String("module-dir", ".", "directory containing go.mod")
	output := flag.String("output", "THIRD_PARTY_NOTICES.md", "output path, relative to the current directory")
	flag.Parse()
	deps := map[string]*dependency{}
	// Union of the release platforms, including platform-specific imports.
	for _, target := range []string{"linux/amd64", "linux/arm64", "darwin/amd64", "darwin/arm64", "windows/amd64", "windows/arm64"} {
		parts := strings.Split(target, "/")
		cmd := exec.Command("go", "list", "-mod=readonly", "-buildvcs=false", "-deps", "-json", "./...")
		cmd.Dir = *moduleDir
		cmd.Env = environment(map[string]string{"GOOS": parts[0], "GOARCH": parts[1], "CGO_ENABLED": "0", "GOWORK": "off"})
		var stderr bytes.Buffer
		cmd.Stderr = &stderr
		data, err := cmd.Output()
		if err != nil {
			return fmt.Errorf("list dependencies for %s: %w\n%s", target, err, stderr.String())
		}
		decoder := json.NewDecoder(bytes.NewReader(data))
		for {
			var p pkg
			if err := decoder.Decode(&p); err == io.EOF {
				break
			} else if err != nil {
				return err
			}
			if p.Standard || p.Module == nil || p.Module.Main {
				continue
			}
			m := *p.Module
			if m.Replace != nil {
				return fmt.Errorf("%s is replaced; review its actual source and notices before distributing", m.Path)
			}
			key := m.Path + "@" + m.Version
			d := deps[key]
			if d == nil {
				d = &dependency{Module: m, Files: map[string]string{}}
				deps[key] = d
			}
			// Preserve module-wide and package-specific notices. Do not scan unrelated
			// testdata or vendor trees, which are not part of this build.
			for dir := p.Dir; ; dir = filepath.Dir(dir) {
				rel, err := filepath.Rel(m.Dir, dir)
				if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
					return fmt.Errorf("package directory outside module %s: %s", key, dir)
				}
				if err := collect(dir, m.Dir, d.Files); err != nil {
					return err
				}
				if rel == "." {
					break
				}
			}
		}
	}
	var b strings.Builder
	b.WriteString("# Third-party notices\n\nGenerated by `go run scripts/licenses.go`. Do not edit the generated text.\n\n")
	b.WriteString("The project's original code is licensed under MIT (see LICENSE). Dependencies retain their own licenses. This file contains the union of notices for normal Go builds on Linux, macOS and Windows, amd64 and arm64, with CGO disabled. It excludes test-only dependencies, external executables and container images. Package ancestry is used to find legal files; source provenance and licenses embedded only in source comments still require review.\n\n")
	b.WriteString("For each module, the source archive below provides its exact, unmodified version, including the upstream license files. In particular, recipients of binaries containing MPL-2.0 components may obtain their MPL-covered source from these archives. Any future modifications to MPL-covered files must also be made available under MPL-2.0.\n\n")
	keys := sortedKeys(deps)
	b.WriteString("| Module | Version | Source |\n|---|---|---|\n")
	for _, key := range keys {
		m := deps[key].Module
		fmt.Fprintf(&b, "| %s | %s | [source archive](%s) |\n", m.Path, m.Version, sourceURL(m))
	}
	goRootCmd := exec.Command("go", "env", "GOROOT")
	goRoot, err := goRootCmd.Output()
	if err != nil {
		return err
	}
	goLicense, err := os.ReadFile(filepath.Join(strings.TrimSpace(string(goRoot)), "LICENSE"))
	if err != nil {
		return err
	}
	b.WriteString("\n## Go runtime and standard library\n\nSource: https://go.dev/dl/ (use the Go version recorded by `go version -m` on the binary).\n\n")
	writeText(&b, "LICENSE", string(goLicense))
	for _, key := range keys {
		d := deps[key]
		if len(d.Files) == 0 {
			return fmt.Errorf("no nonempty license/notice found for %s; resolve its license before distributing", key)
		}
		fmt.Fprintf(&b, "\n## %s\n\nSource: %s\n\n", key, sourceURL(d.Module))
		for _, name := range sortedKeys(d.Files) {
			writeText(&b, name, d.Files[name])
		}
	}
	result := []byte(strings.TrimRight(b.String(), "\n") + "\n")
	if *check {
		current, err := os.ReadFile(*output)
		if err != nil {
			return err
		}
		if !bytes.Equal(bytes.ReplaceAll(current, []byte("\r\n"), []byte("\n")), result) {
			return fmt.Errorf("%s is stale; regenerate it with go run scripts/licenses.go", *output)
		}
		fmt.Printf("Checked %s (%d dependency modules)\n", *output, len(keys))
		return nil
	}
	if err := os.WriteFile(*output, result, 0644); err != nil {
		return err
	}
	fmt.Printf("Generated %s (%d dependency modules)\n", *output, len(keys))
	return nil
}

func collect(dir, root string, files map[string]string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := strings.ToUpper(entry.Name())
		if !(strings.HasPrefix(name, "LICENSE") || strings.HasPrefix(name, "LICENCE") || strings.HasPrefix(name, "COPYING") || strings.HasPrefix(name, "NOTICE") || strings.HasPrefix(name, "COPYRIGHT") || name == "SQLITE-LICENSE" || name == "_EXTRA_CREDITS") {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if _, exists := files[rel]; exists {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.TrimSpace(string(data)) != "" {
			files[rel] = string(data)
		}
	}
	return nil
}

func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sourceURL(m module) string {
	var escaped strings.Builder
	for _, c := range m.Path {
		if c >= 'A' && c <= 'Z' {
			escaped.WriteByte('!')
			escaped.WriteRune(c + ('a' - 'A'))
		} else {
			escaped.WriteRune(c)
		}
	}
	return "https://proxy.golang.org/" + escaped.String() + "/@v/" + m.Version + ".zip"
}

func writeText(b *strings.Builder, name, text string) {
	text = strings.ReplaceAll(text, "\r\n", "\n")
	// Choose a fence longer than any run in the upstream text.
	fence := "```"
	for strings.Contains(text, fence) {
		fence += "`"
	}
	fmt.Fprintf(b, "### %s\n\n%stext\n%s\n%s\n\n", name, fence, strings.TrimRight(text, "\n"), fence)
}

func environment(values map[string]string) []string {
	var env []string
	for _, item := range os.Environ() {
		name, _, _ := strings.Cut(item, "=")
		keep := true
		for override := range values {
			if strings.EqualFold(name, override) {
				keep = false
			}
		}
		if keep {
			env = append(env, item)
		}
	}
	for _, key := range sortedKeys(values) {
		env = append(env, key+"="+values[key])
	}
	return env
}
