// openapi-doc は OpenAPI 3.0 定義から、手順書 (Quarto book) に取り込む API 仕様の原稿を作る。
//
//	go run ./tools/openapi-doc -in openapi/library-api.yaml -out docs/generated/api/api-spec.qmd
//
// 本サンプルの OpenAPI で使っている範囲 ($ref、path/query パラメータ、JSON の
// requestBody・responses・example、object/array スキーマ) だけを扱う簡易変換である。
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type node = map[string]any

var (
	spec node
	doc  yaml.Node // キーの記述順を得るための生の YAML
)

func main() {
	in := flag.String("in", "openapi/library-api.yaml", "OpenAPI ファイル")
	out := flag.String("out", "docs/generated/api/api-spec.qmd", "出力する .qmd")
	flag.Parse()

	data, err := os.ReadFile(*in)
	if err != nil {
		log.Fatal(err)
	}
	if err := yaml.Unmarshal(data, &spec); err != nil {
		log.Fatal(err)
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- Code generated by tools/openapi-doc from %s; DO NOT EDIT. -->\n\n", filepath.ToSlash(*in))
	writeSummary(&b)
	writeOperations(&b)
	writeSchemas(&b)

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s\n", *out)
}

type operation struct {
	tag, method, path, id string
	op                    node
	params                []any
}

var methodOrder = []string{"get", "post", "put", "patch", "delete"}

// operations は tags の定義順 → パス定義順 → メソッド順で並べた operation を返す。
func operations() []operation {
	tagIndex := map[string]int{}
	for i, t := range list(spec["tags"]) {
		tagIndex[str(m(t)["name"])] = i
	}
	paths := m(spec["paths"])
	var keys []string
	for k := range paths {
		keys = append(keys, k)
	}
	pathIndex := orderOf("paths")
	sort.SliceStable(keys, func(i, j int) bool { return pathIndex[keys[i]] < pathIndex[keys[j]] })

	var ops []operation
	for _, p := range keys {
		item := m(paths[p])
		for _, meth := range methodOrder {
			op := m(item[meth])
			if op == nil {
				continue
			}
			tag := ""
			if tags := list(op["tags"]); len(tags) > 0 {
				tag = str(tags[0])
			}
			ops = append(ops, operation{tag: tag, method: strings.ToUpper(meth), path: p, id: str(op["operationId"]), op: op,
				params: append(list(item["parameters"]), list(op["parameters"])...)})
		}
	}
	sort.SliceStable(ops, func(i, j int) bool { return tagIndex[ops[i].tag] < tagIndex[ops[j].tag] })
	return ops
}

func writeSummary(b *bytes.Buffer) {
	info := m(spec["info"])
	fmt.Fprintf(b, "## API の概要 {#sec-api-summary}\n\n")
	fmt.Fprintf(b, "%s（版 %s）\n\n", str(info["title"]), str(info["version"]))
	if d := strings.TrimSpace(str(info["description"])); d != "" {
		fmt.Fprintf(b, "%s\n\n", d)
	}
	fmt.Fprintf(b, "| 接続先 | 説明 |\n|---|---|\n")
	for _, s := range list(spec["servers"]) {
		fmt.Fprintf(b, "| `%s` | %s |\n", str(m(s)["url"]), cell(str(m(s)["description"])))
	}
	fmt.Fprintf(b, "\n: 接続先 {#tbl-api-servers}\n\n")

	fmt.Fprintf(b, "| 分類 | メソッド | パス | operationId | 概要 | 応答ステータス |\n|---|---|---|---|---|---|\n")
	for _, o := range operations() {
		fmt.Fprintf(b, "| %s | %s | `%s` | %s | %s | %s |\n", o.tag, o.method, o.path, o.id, cell(str(o.op["summary"])),
			strings.Join(statuses(o.op), ", "))
	}
	fmt.Fprintf(b, "\n: API 一覧 {#tbl-api-list}\n\n")
}

func writeOperations(b *bytes.Buffer) {
	fmt.Fprintf(b, "## 各 API の仕様 {#sec-api-operations}\n\n")
	for _, o := range operations() {
		fmt.Fprintf(b, "### %s %s（%s） {#sec-api-%s}\n\n", o.method, o.path, str(o.op["summary"]), strings.ToLower(o.id))
		if d := strings.TrimSpace(str(o.op["description"])); d != "" {
			fmt.Fprintf(b, "%s\n\n", d)
		}
		if len(o.params) > 0 {
			fmt.Fprintf(b, "| 名前 | 位置 | 必須 | 型 | 制約 | 説明 | 例 |\n|---|---|---|---|---|---|---|\n")
			for _, p := range o.params {
				pm := resolve(p)
				sc := resolve(pm["schema"])
				fmt.Fprintf(b, "| %s | %s | %s | %s | %s | %s | %s |\n", str(pm["name"]), str(pm["in"]), yes(pm["required"]),
					typeOf(sc), cell(constraints(sc)), cell(str(pm["description"])), cell(scalar(pm["example"])))
			}
			fmt.Fprintf(b, "\n: %s のパラメータ {#tbl-api-%s-params}\n\n", o.id, strings.ToLower(o.id))
		}
		if rb := m(o.op["requestBody"]); rb != nil {
			mt := m(m(rb["content"])["application/json"])
			fmt.Fprintf(b, "リクエストボディ（application/json、%s）：%s\n\n", map[bool]string{true: "必須", false: "任意"}[rb["required"] == true], schemaRef(mt["schema"]))
			if ex, ok := mt["example"]; ok {
				fmt.Fprintf(b, "```json\n%s\n```\n\n", pretty(ex))
			}
		}
		fmt.Fprintf(b, "| ステータス | 説明 | 応答スキーマ | 例 |\n|---|---|---|---|\n")
		resps := m(o.op["responses"])
		for _, code := range statuses(o.op) {
			r := resolve(resps[code])
			mt := m(m(r["content"])["application/json"])
			ex := ""
			if v, ok := mt["example"]; ok {
				ex = "`" + compact(v) + "`"
			}
			fmt.Fprintf(b, "| %s | %s | %s | %s |\n", code, cell(str(r["description"])), schemaRef(mt["schema"]), cell(ex))
		}
		fmt.Fprintf(b, "\n: %s の応答 {#tbl-api-%s-responses}\n\n", o.id, strings.ToLower(o.id))
	}
}

func writeSchemas(b *bytes.Buffer) {
	fmt.Fprintf(b, "## データ定義 {#sec-api-schemas}\n\n")
	schemas := m(m(spec["components"])["schemas"])
	order := orderOf("components", "schemas")
	var names []string
	for k := range schemas {
		names = append(names, k)
	}
	sort.SliceStable(names, func(i, j int) bool { return order[names[i]] < order[names[j]] })
	for _, name := range names {
		sc := m(schemas[name])
		req := map[string]bool{}
		for _, r := range list(sc["required"]) {
			req[str(r)] = true
		}
		fmt.Fprintf(b, "### %s {#sec-api-schema-%s}\n\n", name, strings.ToLower(name))
		fmt.Fprintf(b, "| 項目 | 型 | 必須 | 制約 | 説明 |\n|---|---|---|---|---|\n")
		props := m(sc["properties"])
		porder := orderOf("components", "schemas", name, "properties")
		var keys []string
		for k := range props {
			keys = append(keys, k)
		}
		sort.SliceStable(keys, func(i, j int) bool { return porder[keys[i]] < porder[keys[j]] })
		for _, k := range keys {
			p := m(props[k])
			fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n", k, typeOf(p), yes(req[k]), cell(constraints(p)), cell(str(p["description"])))
		}
		fmt.Fprintf(b, "\n: %s {#tbl-api-schema-%s}\n\n", name, strings.ToLower(name))
	}
}

// ---------------------------------------------------------------- helpers

func statuses(op node) []string {
	var codes []string
	for k := range m(op["responses"]) {
		codes = append(codes, k)
	}
	sort.Strings(codes)
	return codes
}

func resolve(v any) node {
	n := m(v)
	ref := str(n["$ref"])
	if ref == "" {
		return n
	}
	cur := any(spec)
	for _, seg := range strings.Split(strings.TrimPrefix(ref, "#/"), "/") {
		cur = m(cur)[seg]
	}
	return resolve(cur)
}

func schemaRef(v any) string {
	n := m(v)
	if ref := str(n["$ref"]); ref != "" {
		name := ref[strings.LastIndex(ref, "/")+1:]
		return fmt.Sprintf("%s（@sec-api-schema-%s）", name, strings.ToLower(name))
	}
	if n == nil {
		return "-"
	}
	return typeOf(n)
}

func typeOf(sc node) string {
	if ref := str(sc["$ref"]); ref != "" {
		return schemaRef(sc)
	}
	t := str(sc["type"])
	if t == "array" {
		return schemaRef(sc["items"]) + " の配列"
	}
	if f := str(sc["format"]); f != "" {
		t += "(" + f + ")"
	}
	if sc["nullable"] == true {
		t += "、null 可"
	}
	return t
}

func constraints(sc node) string {
	var c []string
	if e := list(sc["enum"]); len(e) > 0 {
		var vs []string
		for _, v := range e {
			vs = append(vs, str(v))
		}
		c = append(c, "値: "+strings.Join(vs, " / "))
	}
	if p := str(sc["pattern"]); p != "" {
		c = append(c, "形式: `"+p+"`")
	}
	if v, ok := sc["minimum"]; ok {
		c = append(c, fmt.Sprintf("最小 %v", v))
	}
	if v, ok := sc["maximum"]; ok {
		c = append(c, fmt.Sprintf("最大 %v", v))
	}
	if v, ok := sc["maxLength"]; ok {
		c = append(c, fmt.Sprintf("最大長 %v", v))
	}
	return strings.Join(c, "、")
}

// orderOf は YAML 上のキーの記述順を返す (map に読み込むと順序が失われるため)。
func orderOf(path ...string) map[string]int {
	idx := map[string]int{}
	if len(doc.Content) == 0 {
		return idx
	}
	cur := doc.Content[0]
	for _, key := range path {
		var next *yaml.Node
		for i := 0; i+1 < len(cur.Content); i += 2 {
			if cur.Content[i].Value == key {
				next = cur.Content[i+1]
			}
		}
		if next == nil {
			return idx
		}
		cur = next
	}
	for i := 0; i+1 < len(cur.Content); i += 2 {
		idx[cur.Content[i].Value] = i
	}
	return idx
}

func m(v any) node {
	n, _ := v.(node)
	return n
}

func list(v any) []any {
	l, _ := v.([]any)
	return l
}

func str(v any) string {
	if v == nil {
		return ""
	}
	return fmt.Sprint(v)
}

func scalar(v any) string {
	if v == nil {
		return ""
	}
	return "`" + fmt.Sprint(v) + "`"
}

func yes(v any) string {
	if v == true {
		return "○"
	}
	return ""
}

func cell(s string) string {
	s = strings.ReplaceAll(strings.TrimSpace(s), "\n", " ")
	return strings.ReplaceAll(s, "|", "\\|")
}

func pretty(v any) string {
	out, _ := json.MarshalIndent(v, "", "  ")
	return string(out)
}

func compact(v any) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(v)
	return strings.TrimSpace(buf.String())
}
