project:
  type: book
  output-dir: _book
book:
  title: gRPC E2E テスト手順書
  chapters:
    - index.qmd
    - unary.qmd
    - server-streaming.qmd
    - calculation-streaming.qmd
    - series-analysis.qmd
lang: ja
format:
  html:
    toc: true
    css: design-doc.css
filters:
  - workflow-layout.lua
  - design-doc.lua
